import type { Metadata } from "next";
import "./globals.css";
import FloatingNavbar from "@/components/Navbar"; 
import Header from "@/components/header";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sans antialiased`}>
        <SessionProvider>
        <Header/>
        {children}
        <FloatingNavbar></FloatingNavbar>
        </SessionProvider>
      </body>
    </html>
  );
}
